// CSS
import "froala-editor/css/froala_editor.min.css";
import "froala-editor/css/froala_style.min.css";
// CSS plugins
import "froala-editor/css/plugins/char_counter.min.css";
import "froala-editor/css/plugins/code_view.min.css";
import "froala-editor/css/plugins/colors.min.css";
import "froala-editor/css/plugins/draggable.min.css";
import "froala-editor/css/plugins/emoticons.min.css";
import "froala-editor/css/plugins/file.min.css";
import "froala-editor/css/plugins/fullscreen.min.css";
import "froala-editor/css/plugins/help.min.css";
import "froala-editor/css/plugins/image.min.css";
import "froala-editor/css/plugins/image_manager.min.css";
import "froala-editor/css/plugins/line_breaker.min.css";
import "froala-editor/css/plugins/quick_insert.min.css";
import "froala-editor/css/plugins/special_characters.min.css";
import "froala-editor/css/plugins/table.min.css";
import "froala-editor/css/plugins/video.min.css";
// JS plugins
import "froala-editor/js/plugins/align.min";
import "froala-editor/js/plugins/char_counter.min";
import "froala-editor/js/plugins/code_beautifier.min";
import "froala-editor/js/plugins/code_view.min";
import "froala-editor/js/plugins/colors.min";
import "froala-editor/js/plugins/draggable.min";
import "froala-editor/js/plugins/emoticons.min";
import "froala-editor/js/plugins/entities.min";
import "froala-editor/js/plugins/file.min";
import "froala-editor/js/plugins/font_family.min";
import "froala-editor/js/plugins/font_size.min";
import "froala-editor/js/plugins/forms.min";
import "froala-editor/js/plugins/fullscreen.min";
import "froala-editor/js/plugins/help.min";
import "froala-editor/js/plugins/image.min";
import "froala-editor/js/plugins/image_manager.min";
import "froala-editor/js/plugins/inline_style.min";
import "froala-editor/js/plugins/line_breaker.min";
import "froala-editor/js/plugins/link.min";
import "froala-editor/js/plugins/lists.min";
import "froala-editor/js/plugins/paragraph_format.min";
import "froala-editor/js/plugins/paragraph_style.min";
import "froala-editor/js/plugins/print.min";
import "froala-editor/js/plugins/quick_insert.min";
import "froala-editor/js/plugins/quote.min";
import "froala-editor/js/plugins/save.min";
import "froala-editor/js/plugins/special_characters.min";
import "froala-editor/js/plugins/table.min";
import "froala-editor/js/plugins/url.min";
import "froala-editor/js/plugins/video.min";
import "froala-editor/js/plugins/word_paste.min";
// languages
import "froala-editor/js/languages/zh_tw"
